version: '3.8'

services:
  postgis-db:
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data

  courier-tracking-app:
    build: ./
    restart: unless-stopped
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgis-db:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgis-db

volumes:
  postgis-data:
