name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger VPS Build
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd Projects/courier-tracking
          ./deploy.sh
